# Generated by Django 5.2.4 on 2025-07-16 14:37

import apps.players.models
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('resources', django_mongodb_backend.fields.EmbeddedModelField(default=apps.players.models.Resources, embedded_model=apps.players.models.Resources, help_text="Player's available resources")),
                ('buildings', django_mongodb_backend.fields.EmbeddedModelArrayField(blank=True, default=list, embedded_model=apps.players.models.PlayerBuilding, help_text='List of buildings the player has started or completed', unique=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='PlayerBuilding',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(help_text='Reference to Building.id', max_length=24)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', help_text='Current build status', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finish_eta', models.DateTimeField(help_text='Expected completion datetime')),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task id for scheduled completion', max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wood', models.PositiveIntegerField(default=1000)),
                ('stone', models.PositiveIntegerField(default=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
