# Generated by Django 5.2.4 on 2025-07-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['username'], name='players_pla_usernam_5bba13_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['email'], name='players_pla_email_f0fd40_idx'),
        ),
    ]
