# Generated by Django 5.2.4 on 2025-07-16 20:31

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('building_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('build_time', models.PositiveIntegerField(help_text='Time to complete building in seconds')),
                ('required_wood', models.PositiveIntegerField()),
                ('required_stone', models.PositiveIntegerField()),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='List of Building IDs that this building depends on (by building_id)')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['name'],
            },
        ),
    ]
